export const SELECT_FUNCTION = 'SELECT_FUNCTION';
export const SELECT_BODYZONES = 'SELECT_BODYZONES';
export const SELECT_FABRICATION = 'SELECT_FABRICATION';
export const SELECT_MATERIAL = 'SELECT_MATERIAL';
