export const SELECT_FUNCTION = 'SELECT_FUNCTION';
export const SELECT_BODYZONES = 'SELECT_BODYZONES';
export const SELECT_FABRICATION = 'SELECT_FABRICATION';
export const SELECT_MATERIAL = 'SELECT_MATERIAL';

export const SHOW_FUNC = 'SHOW_FUNC';
export const SHOW_BOD = 'SHOW_BOD';
export const SHOW_FAB = 'SHOW_FAB';
export const SHOW_MAT = 'SHOW_MAT';

export const PRE_SELECT_FUNC = 'PRE_SELECT_FUNC';
export const PRE_SELECT_BOD = 'PRE_SELECT_BOD';
export const PRE_SELECT_FAB = 'PRE_SELECT_FAB';
export const PRE_SELECT_MAT = 'PRE_SELECT_MAT';
